"""
core/sdk/room.py
RoomAPI Protocol.
"""
from __future__ import annotations
from datetime import datetime
from typing import List, Optional, Protocol, runtime_checkable
from .types import (AuditEvent, ActionType, Document, DocumentId, Member,
                    Room, RoomId, SensorEvent, SensorId, Task, TaskId, TaskStatus, UserId)

@runtime_checkable
class RoomAPI(Protocol):
    def get_room(self, room_id: RoomId) -> Room: ...
    def list_rooms(self, user_id: UserId) -> List[Room]: ...
    def get_members(self, room_id: RoomId) -> List[Member]: ...
    def read_sensor_data(self, room_id: RoomId, sensor_id: SensorId,
                         since: Optional[datetime] = None, limit: Optional[int] = None) -> List[SensorEvent]: ...
    def write_sensor_event(self, room_id: RoomId, sensor_id: SensorId,
                           user_id: UserId, payload: dict) -> SensorEvent: ...
    def create_task(self, room_id: RoomId, created_by: UserId, title: str,
                    description: str, assigned_to: Optional[UserId] = None,
                    due_at: Optional[datetime] = None) -> Task: ...
    def update_task_status(self, room_id: RoomId, task_id: TaskId,
                           updated_by: UserId, new_status: TaskStatus) -> Task: ...
    def list_tasks(self, room_id: RoomId, status: Optional[TaskStatus] = None) -> List[Task]: ...
    def get_task(self, room_id: RoomId, task_id: TaskId) -> Task: ...
    def upload_document(self, room_id: RoomId, uploaded_by: UserId,
                        name: str, file_path: str, notes: str = "") -> Document: ...
    def get_document(self, room_id: RoomId, document_id: DocumentId) -> Document: ...
    def list_documents(self, room_id: RoomId) -> List[Document]: ...
    def get_audit_trail(self, room_id: RoomId, since: Optional[datetime] = None,
                        action_types: Optional[List[ActionType]] = None) -> List[AuditEvent]: ...
