"""
core/sdk/sensor.py
Sensor primitives.
"""
from __future__ import annotations
from datetime import datetime
from typing import Any, Dict, List, Optional, Protocol, runtime_checkable
from .types import RoomId, SensorEvent, SensorId

@runtime_checkable
class SensorPrimitive(Protocol):
    sensor_id: SensorId
    room_id:   RoomId
    label:     str
    def get_schema(self) -> Dict[str, Any]: ...
    def validate(self, payload: Dict[str, Any]) -> bool: ...
    def on_submit(self, event: SensorEvent, room_api: Any) -> None: ...

@runtime_checkable
class FormSensorPrimitive(Protocol):
    sensor_id: SensorId
    room_id:   RoomId
    label:     str
    schema:    Dict[str, Any]
    def get_schema(self) -> Dict[str, Any]: ...
    def validate(self, payload: Dict[str, Any]) -> bool: ...
    def on_submit(self, event: SensorEvent, room_api: Any) -> None: ...

@runtime_checkable
class QRTriggerPrimitive(Protocol):
    sensor_id: SensorId
    room_id:   RoomId
    label:     str
    def generate_qr(self, entity_id: str) -> bytes: ...
    def decode_qr(self, qr_data: str) -> Dict[str, Any]: ...
    def on_scan(self, qr_data: str, room_api: Any) -> SensorEvent: ...
    def get_schema(self) -> Dict[str, Any]: ...
    def validate(self, payload: Dict[str, Any]) -> bool: ...
    def on_submit(self, event: SensorEvent, room_api: Any) -> None: ...

@runtime_checkable
class DocumentSensorPrimitive(Protocol):
    sensor_id:          SensorId
    room_id:            RoomId
    label:              str
    allowed_extensions: List[str]
    max_file_size_mb:   float
    def validate(self, payload: Dict[str, Any]) -> bool: ...
    def on_upload(self, event: SensorEvent, room_api: Any) -> None: ...
    def get_schema(self) -> Dict[str, Any]: ...
    def on_submit(self, event: SensorEvent, room_api: Any) -> None: ...
    def get_versions(self, document_id: str, room_api: Any) -> List[Any]: ...

@runtime_checkable
class PhotoCheckInPrimitive(Protocol):
    sensor_id:             SensorId
    room_id:               RoomId
    label:                 str
    stale_threshold_hours: int
    def on_checkin(self, entity_id: str, photo_bytes: bytes, user_id: Any,
                   room_api: Any, gps_lat: Optional[float] = None, gps_lon: Optional[float] = None) -> SensorEvent: ...
    def get_last_checkin(self, entity_id: str, room_api: Any) -> Optional[SensorEvent]: ...
    def get_stale_entities(self, entity_ids: List[str], as_of: datetime, room_api: Any) -> List[str]: ...
    def get_schema(self) -> Dict[str, Any]: ...
    def validate(self, payload: Dict[str, Any]) -> bool: ...
    def on_submit(self, event: SensorEvent, room_api: Any) -> None: ...
